base_vagrantfile = '../../..Vagrantfile'
load base_vagrantfile if File.exists?(base_vagrantfile)

Vagrant.configure("2") do |config|
  # Mount the local directory
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Provision the VM
  config.vm.provision "shell", inline: <<-SHELL
    # Change directory to the mounted location
    cd /vagrant

    # Install everything required for this build
    ./scripts/prepare.sh

    # Run the kernel compilation script
    ./scripts/compile.sh -v $(uname -r | cut -d'-' -f1)
  SHELL
end
